### ISSUE TITLE
Integration with nixpkgs

### ISSUE THREAD

**Issue by happysalada** [ydlr/mix2nix#1]
Hi, what would you think of integrating this in nixpkgs?
I've recently checked with the elixir mailing list, and it seems that the mix.lock format is stable.
I would be interested in helping you getting this merged and maintaining this of course.
If you don't feel like it for any reason, no worries!

**Comment by ydlr** [comment]
I am fine with adding it to nixpkgs. I've honestly never considered it. It is such a simple little utility and I had no idea anyone else was using it.

I can submit it this weekend, unless you wanted to do it yourself. If I do submit it, would you like me to list you as a maintainer?

**Comment by happysalada** [comment]
Handling all the complex edge cases might take time, and increase the scope (I don't know how much you have tested it).

There is a beam maintainer team, I would say add it as a maintainer. (I am part of it).

Thanks a lot for responding so fast!

**Comment by happysalada** [comment]
Closing this for now as it is not needed
