### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by camelpunch** [ydlr/mix2nix#19]
We're currently overriding the mix2nix derivation in nixpkgs to get [this important fix](https://github.com/ydlr/mix2nix/commit/2fa02649749990e7045fc28eefb83ff9f55d21d3). Is there any chance we could release and get this into nixpkgs?

Happy to help if needed!

**Comment by ydlr** [comment]
Thanks for the reminder. I merged your version string fix and[ submitted a pull request to nixpkgs](https://github.com/NixOS/nixpkgs/pull/258251).

**Comment by camelpunch** [comment]
Thank you!
