### ISSUE TITLE
ssl_verify_fun gets marked as buildMix

### ISSUE THREAD

**Issue by happysalada** [ydlr/mix2nix#2]
I'm not sure what is the best way to proceed.
However this dependency gets marked as buildMix https://github.com/deadtrickster/ssl_verify_fun.erl
the builders doesn't say anything, so there is no way to guess.
I don't know if it is a good idea to include another cond case with `pkgname == "ssl_verify_fun"`.
Just putting it here for reference.

**Comment by happysalada** [comment]
Actually I just did some tests, and the fact that ssl_verify_fun is detected as buildMix can create problems for dependents.

btw
The correct builder is `buildRebar3`

**Comment by happysalada** [comment]
Let me know if you want me to make a PR. I didn't do it out of the box, just because my editor settings are quite different.

**Comment by happysalada** [comment]
Just to give more details here.
buildRebar3 will build it's dependencies into lib/erlang/lib
buildMix will build it's dependencies to _build/$MIX_ENV/lib
If we want to be able to have some buildRebar3 have some dependencies built with buildMix, we would have to duplicate the content of _build/$MIX_ENV/lib into lib/erlang/lib. 
Or we could make buildRebar3 look into it's dependencies into their _build directory.
I don't want to mix the two behaviors, so my initial reaction is to just have ssl_verify_fun use the buildRebar3 builder.

**Comment by ydlr** [comment]
Thanks for letting me know. I'm alright just adding a cond case for ssl_verify_fun. 

I have also been toying with using the buildHex abstraction for all packages so it is easier for users to override which builder is used.

**Comment by ydlr** [comment]
I've added the condition for now. Maybe not the best solution, but it is good enough for now.

**Comment by ydlr** [comment]
It might also be worth considering changing the default builder. I don't remember why I settled on always using mix whenever Hex.pm listed it as an option. Probably to work around some specific package I dealing with at the time.

**Comment by happysalada** [comment]
Thanks a lot for the super fast turnaround!
You're probably right about the default builder. Once we have more feedback from users, we can probably make a better decision.
