### ISSUE TITLE
Same-dir workarounds can be removed soon.

### ISSUE THREAD

**Issue by camelpunch** [ydlr/mix2nix#30]
See https://github.com/NixOS/nixpkgs/pull/306772

The timing of the removal needs some thought, though, since people using a prior version of nixpkgs will still need the workarounds.

**Comment by ydlr** [comment]
Addressed in d1aa138e5b5b0e9c1fbfa8512113501f43181605. I've also made a new release. If someone needs to use an earlier version of nixpkgs, they can stick to the previous release of mix2nix.
