### ISSUE TITLE
Deterministic dependency ordering

### ISSUE THREAD

**Issue by happysalada** [ydlr/mix2nix#5]
Just putting this here so we don't forget.
We should have a deterministic order of the dependencies generated. Whether that is by alphabetical order or not, that is another question.
Basically after an update of the dependencies, the generated deps.nix will show many changes since the order is not deterministic.

**Comment by ydlr** [comment]
Thanks for pointing this out. Resolved with 97ff2859f5d2964c9abd859b7c33b0dd96237129
