### ISSUE TITLE
Formatter troubles

### ISSUE THREAD

**Issue by happysalada** [ydlr/mix2nix#8]
Hey, sorry for the nitpick!
mix2nix is starting to be used!
I noticed the formatting was using tabs, I didn't think it was a problem. However, nixpkgs doesn't seem to like it.
The following PR has a failed check on editorConfig
https://github.com/NixOS/nixpkgs/pull/125934

Perhaps maybe just run nixpkgs-fmt on the output ? (or change the editor settings, but I know that's personal).

One last thing.
Once we figure out the formatting issue, how about publishing a new minor version? I can make the update upstream in nixpkgs.

**Comment by ydlr** [comment]
I suppose I can make this concession to the spaces-preferring barbarians.

**Comment by ydlr** [comment]
https://github.com/NixOS/nixpkgs/pull/126039
